version: '2'

services:
  arduino:
    build: './arduino'
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
  server:
    build: './server'
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
    - "80:80"